server:
  port: 8763
spring:
  application:
    name: eurekaclient
  cloud:
    client:
      ip-address: 127.0.0.1
eureka:
  instance:
    prefer-ip-address: true #是否以ip注册到注册中心，默认是hostname
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #注册限制的实例id
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/ #指定注册中心地址
