server:
  port: 8761
spring:
  application:
    name: eurekaserver
  cloud:
    inetutils:
      preferred-networks: 127.0.0.1
    client:
      ip-address: 127.0.0.1
eureka:
  server:
    peer-node-read-timeout-ms: 3000
    enable-self-preservation: false #是否开启自我保护，注册中心在丢失客户端时不会将服务从注册中心删除掉
  instance:
    prefer-ip-address: true #是否以ip注册到注册中心，默认是hostname
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #注册限制的实例id
  client:
    registerWithEureka: true
    fetchRegistry: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
