server:
  port: 8764

spring:
  application:
    name: patternserver
  cloud:
    client:
      ip-address: 127.0.0.1

logging:
  level:
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
eureka:
  instance:
    prefer-ip-address: true #是否以ip注册到注册中心，默认是hostname
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #注册限制的实例id
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/ #指定注册中心地址


# 自定义starter测试
hello:
  msg: "custom starter test"
