server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    client:
      ip-address: 127.0.0.1
    gateway:
      discovery:
        locator:
          enabled: true #是否与服务发现组件register结合，通过serviceId（必须大写）转发到具体服务实例
#路由访问方式：http://Gateway_host:Gateway_port/大写的serviceId/**
#如：http://localhost:8080/EUREKACLIENT/index
logging:
  level:
    org.springframework.cloud.gateway: true
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
eureka:
  instance:
    prefer-ip-address: true #是否以ip注册到注册中心，默认是hostname
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #注册限制的实例id
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/ #指定注册中心地址
