server:
  port: 8762
spring:
  application:
    name: elasticdemo
  cloud:
    client:
      ip-address: 127.0.0.1
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 127.0.0.1:9300 #程序连接es的端口号
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: admin
      username: 'root'
      password: '123456'

eureka:
  instance:
    prefer-ip-address: false #是否以ip注册到注册中心，默认是hostname
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #注册限制的实例id
  client:
    register-with-eureka: false # 是否注册到Eureka Server
    fetch-registry: false # 是否从Eureka Server获取注册信息，单点-false，集群-true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/ #指定注册中心地址


#es:
#  config:
#    host: localhost
#    port: 9200
#    schema: http
