server:
  port: 8765

spring:
  application:
    name: shiroserver
  cloud:
    client:
      ip-address: 127.0.0.1
  profiles:
    active: test

#  main:
#    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
eureka:
  instance:
    prefer-ip-address: true #是否以ip注册到注册中心，默认是hostname
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #注册限制的实例id
  client:
    register-with-eureka: false # 是否注册到Eureka Server
    fetch-registry: false # 是否从Eureka Server获取注册信息，单点-false，集群-true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/ #指定注册中心地址

shiro:
  loginUrl: /login.html
  userNativeSessionManager: true
  sessionManager:
    sessionIdUrlRewritingEnabled: false

